//
//  SetupInstructionsViewModel.swift
//  XcodeTweaks
//
//  Created by Max Chuquimia on 7/8/2024.
//

import Foundation
import AppKit
import Combine

extension SetupInstructionsView {
    
    @MainActor
    final class ViewModel: ObservableObject {

        @Published var isComplete: Bool = false
        @Published var toggleBuildStarts: Bool = false
        @Published var toggleBuildSucceeds: Bool = false
        @Published var toggleBuildFails: Bool = false
        @Published var savedPath: String = ""

        private var cancellables: Set<AnyCancellable> = []

        init() {
            setup()
        }

    }

}

extension SetupInstructionsView.ViewModel {

    func done() {
        PersistedValues.shared.didSetUpBehaviours = true
    }

    func saveScript() {
        Task(priority: .userInitiated) {
            let executablePath = Bundle.main.bundleURL
                .appending(component: "Contents")
                .appending(component: "MacOS")
                .appending(component: "XcodeTweaks")
                .path

            let script =
            """
            #!/bin/bash

            # This file was automatically generated by XcodeTweaks, but may be edited carefully.
            # You can also call it from other scripts that get called from Xcode Behaviours.
            set -e

            # script_dir="$(dirname $(realpath $0))"
            # cd $script_dir

            # This uses Xcode Behaviours environment variables to determine what operation started or failed.
            \(executablePath) --cli > /tmp/xcodetweaks.log 2>&1
            """
            do {
                try await saveStringAsExecutableScript(content: script)
            } catch {
                print("Error saving script: \(error)")
            }
        }
    }

}

private extension SetupInstructionsView.ViewModel {

    func setup() {
        PersistedValues.shared.$didSetUpBehaviours
            .filter { [weak self] in $0 != self?.isComplete }
            .assign(to: \.isComplete, on: self)
        .store(in: &cancellables)

        // When the user resets the setup, also reset the toggles
        PersistedValues.shared.$didSetUpBehaviours
            .filter { !$0 }
            .sink { _ in
                self.toggleBuildStarts = false
                self.toggleBuildSucceeds = false
                self.toggleBuildFails = false
            }
            .store(in: &cancellables)
    }

    func saveStringAsExecutableScript(content: String) async throws {
        let savePanel = NSSavePanel()
        savePanel.title = "Save Script"
        savePanel.allowedContentTypes = [.shellScript]
        savePanel.nameFieldStringValue = "xcodetweaks-behaviour-script.sh"
        let result = await savePanel.begin()
        if result == .OK, let url = savePanel.url {
            try content.write(to: url, atomically: true, encoding: .utf8)

            // Make the file executable
            let fileAttributes = try FileManager.default.attributesOfItem(atPath: url.path)
            if let currentPermissions = fileAttributes[.posixPermissions] as? NSNumber {
                let newPermissions = currentPermissions.uint16Value | S_IXUSR | S_IXGRP | S_IXOTH
                try FileManager.default.setAttributes([.posixPermissions: newPermissions], ofItemAtPath: url.path)
            }

            savedPath = url.path
        } else {
            throw "Saving file was cancelled."
        }
    }

}
